name: Run Model
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the raw data input topic
    defaultValue: tyre-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: hugging_face_model.py
libraryItemId: hugging-face-model
